#!/bin/bash

set -eux

sudo apt-get -y install nginx-full
tar -xvf $CHARM_DIR/files/grafana-1.9.1.tar.gz -C /opt
sudo sed -i "s|/usr/share/nginx/html|/opt/grafana-1.9.1|g" /etc/nginx/sites-available/default

cp $CHARM_DIR/files/config.js /opt/grafana-1.9.1/config.js
