#!/bin/bash
set -ex

BIN_DIR=/opt/influxdb-injecter/bin
CFG_FILE=$BIN_DIR/cfg
PID_FILE=$BIN_DIR/pid
SERVER=$BIN_DIR/server

ADDR=`relation-get hostname`
PORT=`relation-get port`
NAMESPACE="series-$ADDR"

if [[ $ADDR == "" ]]; then
    juju-log "server not ready to start"
    exit 0
fi

if [[ $PORT == "" ]]; then
    juju-log "server not ready to start"
    exit 0
fi

echo "ADDR=$ADDR" > $CFG_FILE
echo "PORT=$PORT" >> $CFG_FILE

$CHARM_DIR/hooks/stop
$CHARM_DIR/hooks/start
