#!/bin/bash
set -ex

INSTALL_DIR=/opt/influxdb-injecter
CARBON_PID_FILE=$INSTALL_DIR/carbon.pid
INJECTOR_PID_FILE=$INSTALL_DIR/injector.pid
CFG_FILE=$INSTALL_DIR/injector.cfg
BIN_DIR=$INSTALL_DIR/bin
SERVER=$BIN_DIR/server

if [[ -e $CFG_FILE ]]; then
    ADDR=`grep ADDR $CFG_FILE | cut -d'=' -f2`
    PORT=`grep PORT $CFG_FILE | cut -d'=' -f2`
else
    juju-log "server not ready to start"
    exit 0
fi

NAMESPACE="series-$ADDR"

if [[ -e $CARBON_PID_FILE ]]; then
        juju-log "Already started, respawning"
        $CHARM_DIR/hooks/stop
fi

$CHARM_DIR/files/test_carbon.py $ADDR $PORT $NAMESPACE > /dev/null &
PID=$!
juju-log "Starting carbon with pid: $PID"
echo "PID=$PID" > $CARBON_PID_FILE

#PID=$(sudo $SERVER --ns $NAMESPACE --host $ADDR --port $PORT $ADDR $PORT &)
#juju-log "Starting injector with pid: $PID"
#echo "PID=$PID" > $INJECTOR_PID_FILE
