#!/bin/bash
set -ex

BIN_DIR=/opt/influxdb-injecter/bin
PID_FILE=$BIN_DIR/pid

PID=`grep PID $PID_FILE | cut -d'=' -f1`

if [[ -z $PID ]]; then
    # not running
    exit 0
fi

kill -9 $PID
rm $PID_FILE
