#!/bin/bash
set -ex

INSTALL_DIR=/opt/influxdb-injecter
CARBON_PID_FILE=$INSTALL_DIR/carbon.pid
INJECTOR_PID_FILE=$INSTALL_DIR/injector.pid

function stop() {
    PID_FILE=$1
    if [[ -e $PID_FILE ]]; then
        PID=`grep PID $PID_FILE | cut -d'=' -f2`

        if [[ $PID == "" ]]; then
            # not running
            return 0
        fi

        kill -9 $PID
        rm $PID_FILE
    fi
}

stop $INJECTOR_PID_FILE
stop $CARBON_PID_FILE
