#!/bin/bash

set -eux

sudo apt-get -y install nginx-full
tar -xvf $CHARM_DIR/files/grafana-1.9.1.tar.gz -C /opt
sed -e "s|@CHARM_DIR@|$CHARM_DIR|g" $CHARM_DIR/files/nginx_notready | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
